modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="lc_ftb_hook"
version="2.0.0"
displayName="LC FTB Hook"
authors="malik"
description='''Connects Lightman's Currency with FTB Chunks and FTB Teams for paid claims, upkeep, and protection management.'''

[[dependencies.lc_ftb_hook]]
modId="neoforge"
type="required"
versionRange="[21.1.234,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_ftb_hook]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.lc_ftb_hook]]
modId="ftblibrary"
type="required"
versionRange="[2101.1.32,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_ftb_hook]]
modId="ftbteams"
type="required"
versionRange="[2101.1.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_ftb_hook]]
modId="ftbchunks"
type="required"
versionRange="[2101.1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_ftb_hook]]
modId="lightmanscurrency"
type="required"
versionRange="[1.21-2.3.0.4g,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="lc_ftb_hook.mixins.json"
